# Generated by Django 4.1.2 on 2022-12-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=125)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveBigIntegerField()),
                ('status', models.CharField(default='in_stock', max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
