# Generated by Django 4.1.2 on 2022-12-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('on_order', 'Под заказ'), ('receipt_expected', 'Ожидается поступление'), ('not_available', 'Нет в наличии'), ('not_produced', 'Не производится')], default='in_stock', max_length=50),
        ),
    ]
